editAreaLoader.lang["zh_tw"]={
new_document: "開新檔案",
search_button: "尋找與取代",
search_command: "找下一個 / 打開尋找框",
search: "尋找",
replace: "取代",
replace_command: "取代 / 打開取代框",
find_next: "尋找下一個",
replace_all: "全部取代",
reg_exp: "正則表達式",
match_case: "匹配大小寫",
not_found: "未找到.",
occurrence_replaced: "處被取代.",
search_field_empty: "尋找框沒有內容",
restart_search_at_begin: "已到到檔案結尾. 從頭重新尋找.",
move_popup: "移動尋找對話框",
font_size: "--字體大小--",
go_to_line: "轉到行",
go_to_line_prompt: "轉到行:",
undo: "復原",
redo: "重做",
change_smooth_selection: "啟用/關閉一些顯示特性(更好看但更耗費資源)",
highlight: "啟用/關閉語法反白",
reset_highlight: "重置語法反白(當文字顯示不同步時)",
word_wrap: "切换自动换行",
help: "關於",
save: "儲存檔案",
load: "開啟舊檔",
line_abbr: "行",
char_abbr: "字元",
position: "位置",
total: "總計",
close_popup: "關閉對話框",
shortcuts: "快捷鍵",
add_tab: "加入製表符(Tab)",
remove_tab: "移除製表符(Tab)",
about_notice: "注意：語法反白功能僅用於較少內容的文字(文件內容太大會導致瀏覽器反應慢)",
toggle: "切換編輯器",
accesskey: "快捷鍵",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "正在處理中...",
fullscreen: "全螢幕編輯",
syntax_selection: "--語法--",
close_tab: "關閉檔案"
};
